name: "k8s YAML Action"
branding:
  icon: "lock"
  color: "blue"
description: "Generates valid k8s yaml for secrets or configmaps"
inputs:
  name:
    description: Resource name
    required: true
  namespace:
    description: Namespace to put the resource in
    required: true
  secrets:
    description: list of secrets
    required: false
  basic_auth:
    description: Username and password to create a basic auth secret
    required: false
  configmap_env:
    description: Env vars list in the same format as passing secrets but generates configmap
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.name }}
    - ${{ inputs.namespace }}
    - ${{ inputs.secrets }}
    - ${{ inputs.basic_auth }}
    - ${{ inputs.configmap_env }}
