name: Automatically tag and release on merge

on:
  pull_request:
    types:
      - closed
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cloudflared-ssh-action

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tag
        id: tag
        uses: butlerlogic/action-autotag@1.1.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          strategy: regex # Optional since regex_pattern is defined
          root: "CHANGELOG.md"
          regex_pattern: "## ((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)"
      - name: Release
        uses: softprops/action-gh-release@v2
        id: release
        if: ${{ steps.tag.outputs.tagname != '' }}
        with:
          tag_name: tagname
          body_path: CHANGELOG.md
          make_latest: true
      - name: Login to GitHub Packages
        if: ${{ steps.tag.outputs.tagname != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ steps.tag.outputs.tagname != '' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest, ${{ env.REGISTRY }}/${{ github.repository }}:${{steps.tag.outputs.tagname}
