name: Automatically tag and release on merge

on:
  pull_request:
    types:
      - closed
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cloudflared-ssh-action

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate a tag from the latest CHANGELOG.md version
        id: gen-tag
        run: |
          echo tag=$(cat CHANGELOG.md | grep -E -m 1 '^##\s(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$' | cut -c 4- | sed "s/^/v/") >> $GITHUB_OUTPUT
      - name: Push tag to repo
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.gen-tag.outputs.tag}}',
              sha: context.sha
            })
      - name: Release
        uses: softprops/action-gh-release@v2
        id: release
        if: ${{ steps.gen-tag.outputs.tag != '' }}
        with:
          tag_name: ${{steps.gen-tag.outputs.tag}}
          body_path: CHANGELOG.md
          make_latest: true
      - name: Login to GitHub Packages
        if: ${{ steps.tag.outputs.tagname != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ steps.tag.outputs.tagname != '' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest, ${{ env.REGISTRY }}/${{ github.repository }}:${{steps.gen-tag.outputs.tag}}
